/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Interfaces.ABMConfiguracionTipoCaso;

import Controller.ControladorConfiguracionTipoCaso;
import DTO.DTOTipoConfiguracionGrilla;
import java.awt.Color;
import java.awt.Font;
import java.util.List;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;
import main.Menu;

/**
 *
 * @author leand
 */
public class ABMConfiguracionTipoCaso extends javax.swing.JFrame {
    
    DefaultTableModel tablaConfiguraciones;
    ControladorConfiguracionTipoCaso controlador = new ControladorConfiguracionTipoCaso();
    DTOTipoConfiguracionGrilla dtoConfi = new DTOTipoConfiguracionGrilla();

    /** Creates new form ABMConfiguracionTipoCaso */
    public ABMConfiguracionTipoCaso() {
        initComponents();
        setLocationRelativeTo(null); //Este método me permite poder centrar la ventana en la pantalla
        setTitle("ABM Configuracion De Tipo Caso");
        tablaConfiguracion("");    
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaConfiguracionCaso = new javax.swing.JTable();
        botonVolver = new javax.swing.JButton();
        ModificarConfiguracion = new javax.swing.JButton();
        BajaConfiguracion = new javax.swing.JButton();
        ErrorMensaje = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        textTitulo = new javax.swing.JLabel();
        filtroBusqueda = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        AgregarCTC = new javax.swing.JButton();
        botonMostrarDatos = new javax.swing.JButton();
        botonTrabajarRenglo = new javax.swing.JButton();
        botonVerificar = new javax.swing.JButton();

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        tablaConfiguracionCaso = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex){
                return false;
            }
        };
        tablaConfiguracionCaso.setBackground(new java.awt.Color(255, 255, 255));
        tablaConfiguracionCaso.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        tablaConfiguracionCaso.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Núm. Config. TC", "Cod.Tipo Caso", "Fecha Inicio Vigencia", "Fecha Fin Vigencia", "Fecha Verificación"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaConfiguracionCaso.setRowHeight(20);
        tablaConfiguracionCaso.setSelectionBackground(new java.awt.Color(153, 153, 153));
        tablaConfiguracionCaso.setSelectionForeground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(tablaConfiguracionCaso);

        botonVolver.setBackground(new java.awt.Color(204, 204, 204));
        botonVolver.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        botonVolver.setForeground(new java.awt.Color(0, 0, 0));
        botonVolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/baseline_arrow_back_black_18dp.png"))); // NOI18N
        botonVolver.setMnemonic('v');
        botonVolver.setText("Volver");
        botonVolver.setBorder(null);
        botonVolver.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVolverActionPerformed(evt);
            }
        });

        ModificarConfiguracion.setBackground(new java.awt.Color(204, 204, 204));
        ModificarConfiguracion.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        ModificarConfiguracion.setForeground(new java.awt.Color(0, 0, 0));
        ModificarConfiguracion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/baseline_edit_black_18dp.png"))); // NOI18N
        ModificarConfiguracion.setMnemonic('m');
        ModificarConfiguracion.setText("Modificar");
        ModificarConfiguracion.setBorder(null);
        ModificarConfiguracion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ModificarConfiguracion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificarConfiguracionActionPerformed(evt);
            }
        });

        BajaConfiguracion.setBackground(new java.awt.Color(204, 204, 204));
        BajaConfiguracion.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        BajaConfiguracion.setForeground(new java.awt.Color(0, 0, 0));
        BajaConfiguracion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/baseline_delete_black_18dp.png"))); // NOI18N
        BajaConfiguracion.setMnemonic('b');
        BajaConfiguracion.setText("Dar baja");
        BajaConfiguracion.setBorder(null);
        BajaConfiguracion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BajaConfiguracion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BajaConfiguracionActionPerformed(evt);
            }
        });

        ErrorMensaje.setEditable(false);
        ErrorMensaje.setBackground(new java.awt.Color(204, 204, 204));
        ErrorMensaje.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        ErrorMensaje.setBorder(null);
        ErrorMensaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ErrorMensajeActionPerformed(evt);
            }
        });

        jPanel5.setBackground(new java.awt.Color(119, 148, 166));

        textTitulo.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        textTitulo.setForeground(new java.awt.Color(0, 0, 0));
        textTitulo.setText("Configuración Tipo Caso");

        filtroBusqueda.setBackground(new java.awt.Color(255, 255, 255));
        filtroBusqueda.setBorder(null);
        filtroBusqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filtroBusquedaActionPerformed(evt);
            }
        });
        filtroBusqueda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                filtroBusquedaKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                filtroBusquedaKeyReleased(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/baseline_search_black_18dp.png"))); // NOI18N

        AgregarCTC.setBackground(new java.awt.Color(119, 148, 166));
        AgregarCTC.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        AgregarCTC.setForeground(new java.awt.Color(0, 0, 0));
        AgregarCTC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/baseline_add_black_18dp.png"))); // NOI18N
        AgregarCTC.setMnemonic('a');
        AgregarCTC.setText("Agregar");
        AgregarCTC.setBorder(null);
        AgregarCTC.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        AgregarCTC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarCTCActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(textTitulo)
                .addGap(65, 65, 65)
                .addComponent(filtroBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(AgregarCTC, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AgregarCTC)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(filtroBusqueda, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE))))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        botonMostrarDatos.setBackground(new java.awt.Color(204, 204, 204));
        botonMostrarDatos.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        botonMostrarDatos.setForeground(new java.awt.Color(0, 0, 0));
        botonMostrarDatos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/baseline_visibility_black_18dp.png"))); // NOI18N
        botonMostrarDatos.setMnemonic('d');
        botonMostrarDatos.setText("Mostrar Datos");
        botonMostrarDatos.setBorder(null);
        botonMostrarDatos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonMostrarDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonMostrarDatosActionPerformed(evt);
            }
        });

        botonTrabajarRenglo.setBackground(new java.awt.Color(204, 204, 204));
        botonTrabajarRenglo.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        botonTrabajarRenglo.setForeground(new java.awt.Color(0, 0, 0));
        botonTrabajarRenglo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/baseline_edit_black_18dp.png"))); // NOI18N
        botonTrabajarRenglo.setMnemonic('m');
        botonTrabajarRenglo.setText("Trabajar con renglones");
        botonTrabajarRenglo.setBorder(null);
        botonTrabajarRenglo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonTrabajarRenglo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonTrabajarRengloActionPerformed(evt);
            }
        });

        botonVerificar.setBackground(new java.awt.Color(204, 204, 204));
        botonVerificar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        botonVerificar.setForeground(new java.awt.Color(0, 0, 0));
        botonVerificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/baseline_visibility_black_18dp.png"))); // NOI18N
        botonVerificar.setMnemonic('d');
        botonVerificar.setText("Verificar Configuración");
        botonVerificar.setBorder(null);
        botonVerificar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonVerificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVerificarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonVolver)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(ErrorMensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 462, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(205, 205, 205)
                            .addComponent(botonMostrarDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 788, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGap(0, 483, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(botonTrabajarRenglo, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
                                    .addComponent(botonVerificar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ModificarConfiguracion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(BajaConfiguracion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ErrorMensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonMostrarDatos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ModificarConfiguracion)
                    .addComponent(botonVerificar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BajaConfiguracion)
                    .addComponent(botonVolver)
                    .addComponent(botonTrabajarRenglo))
                .addGap(12, 12, 12))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
    public void tablaConfiguracion(String nombreConfi) { //Método de la tabla que se muestra en la interfaz
        List<DTOTipoConfiguracionGrilla> lista = controlador.filtroConfiguracion(nombreConfi);
        tablaConfiguraciones = new DefaultTableModel();
        tablaConfiguracionCaso.setModel(tablaConfiguraciones);
        
        tablaConfiguraciones.addColumn("Num Config. TC");  //Cada una  de las sentencias es una columna en la tabla modelo que instanciamos
        tablaConfiguraciones.addColumn("Cod. Tipo Caso");//que Luego esta tabla le setteamos para mostrar en modelo de la interfaz
        tablaConfiguraciones.addColumn("Fecha Inicio Vigencia");
        tablaConfiguraciones.addColumn("Fecha Fin Vigencia");
        tablaConfiguraciones.addColumn("Fecha Verificacion");

        tablaConfiguracionCaso.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 14));
        tablaConfiguracionCaso.getTableHeader().setBackground(new Color(172, 202, 221));

        tablaConfiguracionCaso.setAutoCreateRowSorter(true);
        tablaConfiguracionCaso.getRowSorter().toggleSortOrder(1);

       for (int i = 0; i < lista.size(); i++) {
            Vector fil = new Vector();
            fil.add(lista.get(i).getNroConfig());
            fil.add(lista.get(i).getCodTipoCaso());
            fil.add(lista.get(i).getFechaInicioVigencia());
            fil.add(lista.get(i).getFechaFinVigencia());
            fil.add(lista.get(i).getFechaVerificacion());
            tablaConfiguraciones.addRow(fil);
      }
    }
    
    
    
    
    private void botonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVolverActionPerformed
        //Método para volver
        Menu menu = new Menu();
        menu.setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_botonVolverActionPerformed

    private void ModificarConfiguracionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarConfiguracionActionPerformed
        //Método para modificar
        int numTabTI = tablaConfiguracionCaso.getSelectedRow();//Almacenamos el numero de la columna en la variable numTabTI
        if (numTabTI == -1) {
            ErrorMensaje.setForeground(Color.RED); //Este sentencia le asigna el color rojo al texto
            ErrorMensaje.setText("No ha seleccionado ningún sector para modificar");
        } else {
            for (int i = 0; i < tablaConfiguracionCaso.getRowCount(); i++) { //Recorremos la tabla
                if (tablaConfiguracionCaso.getValueAt(i, 4) != null) {
                    ErrorMensaje.setForeground(Color.RED);
                    ErrorMensaje.setText("El Tipo instancia esta dado de baja, no se puede modificar");
                } else {
                    if (numTabTI == i) { //comparamos de que el numero almacenado en numTabTI sea igual al numero del arreglo

                        dtoTI.setCodTipoInstancia((int) tablaTI.getValueAt(i, 0));
                        dtoTI.setNombreTipoInstancia((String) tablaTI.getValueAt(i, 1));

                        controlTI.filtradoSector(tablaTI.getValueAt(i, 2).toString());
                        dtoTI.setNombreSector(tablaTI.getValueAt(i, 2).toString());

                        String sec = tablaTI.getValueAt(i, 2).toString();
                        List<DTOTipoInstancia> listamod = controlTI.filtradoSector(sec);
                        for (int j = 0; j < listamod.size(); j++) {
                            DTOTipoInstancia tI = (DTOTipoInstancia) listamod.get(j);
                            dtoTI.setCodSector(tI.getCodSector());
                        }
                        controlTI.filtradoTT(tablaTI.getValueAt(i, 3).toString());
                        String tt = tablaTI.getValueAt(i, 3).toString();
                        List<DTOTipoInstancia> lista = controlTI.filtradoTT(tt);
                        for (int j = 0; j < lista.size(); j++) {
                            DTOTipoInstancia tI = (DTOTipoInstancia) lista.get(j);
                            dtoTI.setCodTipoTarea(tI.getCodTipoTarea());

                        }
                        dtoTI.setNombreTipoTarea(tablaTI.getValueAt(i, 3).toString());

                        System.out.println(dtoTI.getNombreSector());
                        ModificarTipoInstancia mod = new ModificarTipoInstancia(dtoTI);
                        mod.setVisible(true);
                        this.setVisible(false);
                    }

                }
            }
        }
    }//GEN-LAST:event_ModificarConfiguracionActionPerformed

    private void BajaConfiguracionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BajaConfiguracionActionPerformed
        //Método para eliminar
        int numTabSec = tablaConfiguracionCaso.getSelectedRow();//Almacenamos el numero de la columna en la variable numTabSec
        if (numTabSec == -1) {
            ErrorMensaje.setForeground(Color.RED); //Este sentencia le asigna el color rojo al texto
            ErrorMensaje.setText("No ha seleccionado ningún TipoInstancia para dar de baja");

        } else {
            for (int i = 0; i < tablaConfiguracionCaso.getRowCount(); i++) { //Recorremos la tabla
                if (numTabSec == i) { //comparamos de que el numero almacenado en numTabSec sea igual al numero del arreglo
                    if (tablaConfiguracionCaso.getValueAt(i, 4) != null) {
                        ErrorMensaje.setForeground(Color.RED); //Este sentencia le asigna el color rojo al texto
                        ErrorMensaje.setText("El sector elegido ya esta dado de baja");
                    } else {
                        dtoTI.setCodTipoInstancia((int) tablaConfiguracionCaso.getValueAt(i, 0));//el primero del parametro hace referencia a la fila y el segundo a la columna
                        int j = JOptionPane.showConfirmDialog(this,
                            ""
                            + "¿Estas seguro que confirmar la baja? \n\n"
                            + "Cod Tipo Instancia: " + (int) tablaConfiguracionCaso.getValueAt(i, 0) + "\n"
                            + "Nombre Tipo Instancia: " + tablaConfiguracionCaso.getValueAt(i, 1) + "\n"
                            + "Nombre Sector: " + tablaConfiguracionCaso.getValueAt(i, 2) + "\n"
                            + "Nombre Tipo Tarea: " + tablaConfiguracionCaso.getValueAt(i, 3) + "\n\n",
                            "Dar de Baja Tipo Instancia", JOptionPane.YES_NO_OPTION);
                        if (j == 0) {
                            controlTI.bajaTipoInstancia(dtoTI);
                            JOptionPane.showMessageDialog(this, "Sector Dado de baja");
                        }
                        tablaTI("");
                    }
                }
            }
        }
    }//GEN-LAST:event_BajaConfiguracionActionPerformed

    private void filtroBusquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filtroBusquedaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_filtroBusquedaActionPerformed

    private void filtroBusquedaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_filtroBusquedaKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            tablaTI(filBusqueda.getText());
        }
    }//GEN-LAST:event_filtroBusquedaKeyPressed

    private void filtroBusquedaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_filtroBusquedaKeyReleased
        tablaTI(filBusqueda.getText());
    }//GEN-LAST:event_filtroBusquedaKeyReleased

    private void AgregarCTCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarCTCActionPerformed
        //Metodo para agregar un Tipo instancia
        AltaConfiguracionTipocaso agregar = new AltaConfiguracionTipocaso();
        agregar.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_AgregarCTCActionPerformed

    private void botonMostrarDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonMostrarDatosActionPerformed
        //Método Mostrar datos de Sector
        int numTabSec = tablaConfiguracionCaso.getSelectedRow();//Almacenamos el numero de la columna en la variable numTabSec
        if (numTabSec == -1) {
            ErrorMensaje.setForeground(Color.RED); //Este sentencia le asigna el color rojo al texto
            ErrorMensaje.setText("No ha seleccionado ningún TipoInstancia para mostrar");
        } else {
            for (int i = 0; i < tablaConfiguracionCaso.getRowCount(); i++) { //Recorremos la tabla

                if (numTabSec == i) { //comparamos de que el numero almacenado en numTabSec sea igual al numero del arreglo

                    System.out.println(tablaTI.getValueAt(i, 0));
                    System.out.println(tablaTI.getValueAt(i, 1));

                    dtoTI.setCodTipoInstancia((int) tablaTI.getValueAt(i, 0)); //Asigna codigo de tipo Instancia a dto
                    dtoTI.setNombreTipoInstancia((String) tablaTI.getValueAt(i, 1));//Asigna nombre de tipo Instancia a dto
                    dtoTI.setFechaHoraFinVigenciaTI((Date) tablaTI.getValueAt(i, 4));//Asigna fecha fin de TipoInstancia a dto

                    //Inicio busqueda de sector
                    controlTI.filtradoSector(tablaTI.getValueAt(i, 2).toString());
                    String sec = tablaTI.getValueAt(i, 2).toString();
                    List<DTOTipoInstancia> listamod = controlTI.filtradoSector(sec);
                    for (int j = 0; j < listamod.size(); j++) {
                        DTOTipoInstancia tI = (DTOTipoInstancia) listamod.get(j);
                        dtoTI.setCodSector(tI.getCodSector()); //Asigna codigo de Sector a dto
                        dtoTI.setFechaFinVigenciaSector(tI.getFechaFinVigenciaSector());//Asigna fecha fin de sector a dto
                    }
                    dtoTI.setNombreSector(tablaTI.getValueAt(i, 2).toString());//Asigna nombre a sector
                    dtoTI.setNombreTipoTarea(tablaTI.getValueAt(i, 3).toString());//Asigna nombre a Tipo Tarea
                    //Inicio busqueda de TipoTarea

                    controlTI.filtradoTT(tablaTI.getValueAt(i, 3).toString());
                    String tt = tablaTI.getValueAt(i, 3).toString();
                    List<DTOTipoInstancia> lista = controlTI.filtradoTT(tt);
                    for (int l = 0; l < lista.size(); l++) {
                        DTOTipoInstancia tI = (DTOTipoInstancia) lista.get(l);
                        dtoTI.setCodTipoTarea(tI.getCodTipoTarea());//Asigna codigo de tipo Tarea a dto
                        dtoTI.setFechaFinVigenciaTT(tI.getFechaFinVigenciaTT());  //Asigna fecha fin de Tipo Tarea a dto

                    }

                    VerDatosTipoInstancia mostrar = new VerDatosTipoInstancia(dtoTI);
                    mostrar.setVisible(true);

                }

            }
        }
    }//GEN-LAST:event_botonMostrarDatosActionPerformed

    private void botonTrabajarRengloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonTrabajarRengloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonTrabajarRengloActionPerformed

    private void botonVerificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVerificarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonVerificarActionPerformed

    private void ErrorMensajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ErrorMensajeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ErrorMensajeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ABMConfiguracionTipoCaso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ABMConfiguracionTipoCaso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ABMConfiguracionTipoCaso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ABMConfiguracionTipoCaso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ABMConfiguracionTipoCaso().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AgregarCTC;
    private javax.swing.JButton BajaConfiguracion;
    private javax.swing.JTextField ErrorMensaje;
    private javax.swing.JButton ModificarConfiguracion;
    private javax.swing.JButton botonMostrarDatos;
    private javax.swing.JButton botonTrabajarRenglo;
    private javax.swing.JButton botonVerificar;
    private javax.swing.JButton botonVolver;
    private javax.swing.JTextField filtroBusqueda;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaConfiguracionCaso;
    private javax.swing.JLabel textTitulo;
    // End of variables declaration//GEN-END:variables

}
