/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces.ABMConfiguracionTipoCaso;

/**
 *
 * @author leand
 */
public class ModificarRenglon extends javax.swing.JFrame {

    /**
     * Creates new form ModificarRenglon
     */
    public ModificarRenglon() {
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Modificar Renglón");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        labelNroRenglo = new javax.swing.JLabel();
        confirmarModificar = new javax.swing.JButton();
        inputNumRenglon = new javax.swing.JTextField();
        outNombTI = new javax.swing.JTextField();
        inputMinMax = new javax.swing.JTextField();
        labelNombTipoInstancia = new javax.swing.JLabel();
        MensajeError = new javax.swing.JTextField();
        labelCodTipoInstancia = new javax.swing.JLabel();
        labelMinDura = new javax.swing.JLabel();
        inputCodTI = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        volverABM = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        labelNroRenglo.setBackground(new java.awt.Color(0, 0, 0));
        labelNroRenglo.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        labelNroRenglo.setForeground(new java.awt.Color(0, 0, 0));
        labelNroRenglo.setText("Número de renglón:");

        confirmarModificar.setBackground(new java.awt.Color(204, 204, 204));
        confirmarModificar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        confirmarModificar.setForeground(new java.awt.Color(0, 0, 0));
        confirmarModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/baseline_check_black_18dp.png"))); // NOI18N
        confirmarModificar.setMnemonic('c');
        confirmarModificar.setText("Confirmar");
        confirmarModificar.setBorder(null);
        confirmarModificar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        confirmarModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmarModificarActionPerformed(evt);
            }
        });

        inputNumRenglon.setBackground(new java.awt.Color(255, 255, 255));
        inputNumRenglon.setBorder(null);
        inputNumRenglon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputNumRenglonActionPerformed(evt);
            }
        });
        inputNumRenglon.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                inputNumRenglonKeyTyped(evt);
            }
        });

        outNombTI.setEditable(false);
        outNombTI.setBackground(new java.awt.Color(153, 153, 153));
        outNombTI.setBorder(null);
        outNombTI.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                outNombTIFocusLost(evt);
            }
        });
        outNombTI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                outNombTIActionPerformed(evt);
            }
        });
        outNombTI.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                outNombTIKeyTyped(evt);
            }
        });

        inputMinMax.setBackground(new java.awt.Color(255, 255, 255));
        inputMinMax.setBorder(null);
        inputMinMax.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                inputMinMaxFocusLost(evt);
            }
        });
        inputMinMax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputMinMaxActionPerformed(evt);
            }
        });

        labelNombTipoInstancia.setBackground(new java.awt.Color(0, 0, 0));
        labelNombTipoInstancia.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        labelNombTipoInstancia.setForeground(new java.awt.Color(0, 0, 0));
        labelNombTipoInstancia.setText("Nombre Tipo Instancia:");

        MensajeError.setEditable(false);
        MensajeError.setBackground(new java.awt.Color(204, 204, 204));
        MensajeError.setBorder(null);

        labelCodTipoInstancia.setBackground(new java.awt.Color(0, 0, 0));
        labelCodTipoInstancia.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        labelCodTipoInstancia.setForeground(new java.awt.Color(0, 0, 0));
        labelCodTipoInstancia.setText("Cod. Tipo Instancia:");

        labelMinDura.setBackground(new java.awt.Color(0, 0, 0));
        labelMinDura.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        labelMinDura.setForeground(new java.awt.Color(0, 0, 0));
        labelMinDura.setText("Minutos máximos: ");

        inputCodTI.setEditable(false);
        inputCodTI.setBackground(new java.awt.Color(255, 255, 255));
        inputCodTI.setBorder(null);
        inputCodTI.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                inputCodTIFocusLost(evt);
            }
        });
        inputCodTI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputCodTIActionPerformed(evt);
            }
        });
        inputCodTI.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                inputCodTIKeyTyped(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(119, 148, 166));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/baseline_add_black_18dp.png"))); // NOI18N
        jLabel5.setText("MODIFICAR RENGLÓN");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel5)
                .addContainerGap(170, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(33, 33, 33))
        );

        volverABM.setBackground(new java.awt.Color(204, 204, 204));
        volverABM.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        volverABM.setForeground(new java.awt.Color(0, 0, 0));
        volverABM.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/baseline_arrow_back_black_18dp.png"))); // NOI18N
        volverABM.setMnemonic('v');
        volverABM.setText("Volver");
        volverABM.setBorder(null);
        volverABM.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        volverABM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverABMActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(confirmarModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(43, 43, 43)
                                .addComponent(volverABM, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(inputMinMax, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(outNombTI, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelNombTipoInstancia)
                            .addComponent(labelCodTipoInstancia)
                            .addComponent(labelNroRenglo)
                            .addComponent(inputNumRenglon, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelMinDura)
                            .addComponent(inputCodTI, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(MensajeError, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(labelNroRenglo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputNumRenglon, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelMinDura)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(inputCodTI, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(labelCodTipoInstancia)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputMinMax, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(labelNombTipoInstancia)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(outNombTI, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(MensajeError, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(confirmarModificar)
                    .addComponent(volverABM))
                .addGap(15, 15, 15))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void confirmarModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmarModificarActionPerformed
        //Método para agregar un Tipo de Instancia
        /*
        try {
            if (!inputNumRenglon.getText().isEmpty()) {
                if (!inputMinMax.getText().isEmpty()) {
                    if (!inputCodTI.getText().isEmpty()) {
                        if(!inputCodTI.getText().isEmpty()){
                            //int validacion = validarFecha(inputNombreTipoCaso.getText());
                            //if(validacion==1){
                                do{
                                    DTOAgregarConfiguracion dtoAgregar = new DTOAgregarConfiguracion();
                                    dtoAgregar.setNroConfiguracion(Integer.parseInt(inputNumRenglon.getText()));
                                    dtoAgregar.setCodTipoCaso(Integer.parseInt(inputMinMax.getText()));
                                    dtoAgregar.setNombreTipoCaso(inputCodTI.getText());
                                    dtoAgregar.setFechaDesde(fechaDesde.getDate());
                                    dtoE = controlador.agregarConfiguracion(dtoAgregar);
                                    /* SimpleDateFormat objSDF = new SimpleDateFormat("dd/MM/yyyy"); // La cadena de formato de fecha se pasa como un argumento al objeto
                                    String fechaFin = objSDF.format(fechaInicioConfiguracion.getDateFormatString());
                                    SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
                                    Date fechaInicio= dateFormat.parse(fechaInicioConfiguracion.getDate().toString());
                                    String fechaBase = dateFormat.format(fechaInicio);
                                    Date fechaBaseDatos = dateFormat.parse(fechaBase);*/

                                    /*SimpleDateFormat objSDF = new SimpleDateFormat("dd/MM/yyyy");
                                    String fechaFin = objSDF.format(fechaInicioConfiguracion.getDate());
                                    dtoAgregar.setFechaDesde(objSDF.parse(fechaFin));

                                    if(dtoE.getVerificarError() == 0){
                                        JOptionPane.showMessageDialog(this, "La configuración se grabo exitosamente");
                                        ABMConfiguracionTipoCaso abmC = new ABMConfiguracionTipoCaso();
                                        abmC.setVisible(true);
                                        this.setVisible(false);
                                    }else{
                                        MensajeError.setForeground(Color.red);
                                        MensajeError.setText(dtoE.getErrorMensaje());
                                        dtoE.setVerificarError(0);
                                    }

                                }while(dtoE.getVerificarError()!=0);

                            }else{
                                JOptionPane.showMessageDialog(this, "Por favor ingrese una Fecha de Inicio", "Mensaje de Error", JOptionPane.ERROR_MESSAGE);
                            }
                        }else{
                            JOptionPane.showMessageDialog(this, "Por favor ingrese un Codigo Tipo Caso valido", "Mensaje de Error", JOptionPane.ERROR_MESSAGE);
                        }
                    } else {
                        JOptionPane.showMessageDialog(this, "Por favor ingrese un Codigo Tipo Caso", "Mensaje de Error", JOptionPane.ERROR_MESSAGE);
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "Por favor ingrese un Número de Configuración de Tipo Caso", "Mensaje de Error", JOptionPane.ERROR_MESSAGE);
                }

            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e.getMessage());
            }*/
    }//GEN-LAST:event_confirmarModificarActionPerformed

    private void inputNumRenglonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputNumRenglonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputNumRenglonActionPerformed

    private void inputNumRenglonKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputNumRenglonKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_inputNumRenglonKeyTyped

    private void outNombTIFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_outNombTIFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_outNombTIFocusLost

    private void outNombTIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_outNombTIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_outNombTIActionPerformed

    private void outNombTIKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_outNombTIKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_outNombTIKeyTyped

    private void inputMinMaxFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_inputMinMaxFocusLost
        /*   if (!inputMinMax.getText().isEmpty()) {
            MostrarTipoCasoInput(inputMinMax.getText());
        }else{
            JOptionPane.showMessageDialog(this, "Por favor ingrese el código de Tipo Caso", "Mensaje de Error", JOptionPane.ERROR_MESSAGE);
        }*/
    }//GEN-LAST:event_inputMinMaxFocusLost

    private void inputMinMaxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputMinMaxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputMinMaxActionPerformed

    private void inputCodTIFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_inputCodTIFocusLost

    }//GEN-LAST:event_inputCodTIFocusLost

    private void inputCodTIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputCodTIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputCodTIActionPerformed

    private void inputCodTIKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputCodTIKeyTyped
        //Declaramos una variable y asignamos un evento
    }//GEN-LAST:event_inputCodTIKeyTyped

    private void volverABMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverABMActionPerformed

        TrabajarRenglones abmConf = new TrabajarRenglones();
        abmConf.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_volverABMActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModificarRenglon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModificarRenglon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModificarRenglon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModificarRenglon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModificarRenglon().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField MensajeError;
    private javax.swing.JButton confirmarModificar;
    private javax.swing.JTextField inputCodTI;
    private javax.swing.JTextField inputMinMax;
    private javax.swing.JTextField inputNumRenglon;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel labelCodTipoInstancia;
    private javax.swing.JLabel labelMinDura;
    private javax.swing.JLabel labelNombTipoInstancia;
    private javax.swing.JLabel labelNroRenglo;
    private javax.swing.JTextField outNombTI;
    private javax.swing.JButton volverABM;
    // End of variables declaration//GEN-END:variables
}
